### ISSUE TITLE
Dependencies between several steps

### ISSUE THREAD

**Issue by alexanderscholz** [tiennes/uap#36]
With the keyword _depends a dependency between two steps can be defined. For example:
```yaml
fastq_source_1 (fastq_source):
        sample_to_files_map:
            rna_sim_1M:
                - input/SRR014849_1.fastq
        paired_end: no
        first_read: _1.fastq

split_test (split_fastq):
        _depends: fastq_source_1
        readcount: 100000
```
But this implies the transfer of the outfiles from step one to step two as input files! For this reason it is not possible to define two dependencies. For Example:
```yaml
fastq_source_1 (fastq_source):
        sample_to_files_map:
            rna_sim_1M:
                - input/SRR014849_1.fastq
        paired_end: no
        first_read: _1.fastq

split_test1 (split_fastq):
        _depends: fastq_source_1
        readcount: 100000

split_test2 (split_fastq):
        _depends: [fastq_source_1, split_test1]
        readcount: 100
```
